version: "3.3"
services:
  mysqldb:
    container_name: mysqldb
    image: "mysql:latest"
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: eventdb
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
  spring:
    container_name: springp
    build: ./
    restart: always
    ports:
      - 8089:8089
    depends_on:
      - mysqldb
